"""戦略プラグインの基底クラス（全戦略はこのBaseStrategyを継承して実装する）"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    ticker: str
    action: str  # "BUY", "SELL", "HOLD"
    confidence: float  # 0.0 - 1.0
    stop_loss: float  # price level
    take_profit: float  # price level
    reason: str  # human-readable explanation
    price: float = 0.0  # entry price at signal generation time
    take_profit_1: float = 0.0  # 段階利確の第1ターゲット（0 = 未使用）
    max_hold_days: int = 20  # 最大保有日数（超過で強制決済）
    screen_score: float = 0.0  # スクリーニングスコア（発注優先度に使用）

    def __post_init__(self):
        # numpy型がそのままDBに渡されるとエラーになるため Python ネイティブ型に変換
        self.confidence = float(self.confidence)
        self.stop_loss = float(self.stop_loss)
        self.take_profit = float(self.take_profit)
        self.price = float(self.price)
        self.take_profit_1 = float(self.take_profit_1)
        self.screen_score = float(self.screen_score)


@dataclass
class ExitDecision:
    """戦略固有のエグジット判定結果。"""

    should_exit: bool
    reason: str = ""
    suppress_tp: bool = False  # True = 戦略がTP判定を管理、デフォルトTPチェックをスキップ


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    To create a new strategy:
    1. Create a .py file in src/strategy/plugins/
    2. Subclass BaseStrategy
    3. Set name, version, target_regime
    4. Implement generate_signals() and get_params()

    The strategy will be auto-discovered and registered.
    """

    name: str = "unnamed"
    version: str = "1.0"
    target_regime: str = "any"  # "trending", "range", "volatile", "any"

    @abstractmethod
    def generate_signals(
        self, ticker: str, df: pd.DataFrame, market_condition: dict
    ) -> Signal | None:
        """Analyze price data and generate a trading signal.

        Args:
            ticker: Stock ticker symbol
            df: OHLCV DataFrame (DatetimeIndex, columns: Open/High/Low/Close/Volume)
            market_condition: Dict with keys: regime, sp500_trend, vix_level

        Returns:
            Signal if action should be taken, None otherwise.
        """
        ...

    def check_exit(
        self, ticker: str, df: pd.DataFrame, trade_info: dict
    ) -> ExitDecision | None:
        """戦略固有のエグジット条件をチェック。

        Noneを返すとデフォルトのSL/TP/max_holdロジックが適用される。
        ExitDecisionを返すと戦略が判定を上書きできる。
        """
        return None

    @abstractmethod
    def get_params(self) -> dict:
        """Return current strategy parameters (for backtest logging)."""
        ...
