"""戦略プラグインの基底クラス（全戦略はこのBaseStrategyを継承して実装する）"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    ticker: str
    action: str  # "BUY", "SELL", "HOLD"
    confidence: float  # 0.0 - 1.0
    stop_loss: float  # price level
    take_profit: float  # price level
    reason: str  # human-readable explanation
    price: float = 0.0  # entry price at signal generation time


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    To create a new strategy:
    1. Create a .py file in src/strategy/plugins/
    2. Subclass BaseStrategy
    3. Set name, version, target_regime
    4. Implement generate_signals() and get_params()

    The strategy will be auto-discovered and registered.
    """

    name: str = "unnamed"
    version: str = "1.0"
    target_regime: str = "any"  # "trending", "range", "volatile", "any"

    @abstractmethod
    def generate_signals(
        self, ticker: str, df: pd.DataFrame, market_condition: dict
    ) -> Signal | None:
        """Analyze price data and generate a trading signal.

        Args:
            ticker: Stock ticker symbol
            df: OHLCV DataFrame (DatetimeIndex, columns: Open/High/Low/Close/Volume)
            market_condition: Dict with keys: regime, sp500_trend, vix_level

        Returns:
            Signal if action should be taken, None otherwise.
        """
        ...

    @abstractmethod
    def get_params(self) -> dict:
        """Return current strategy parameters (for backtest logging)."""
        ...
